ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ITEM);

ALTER TABLE LOC ADD CONSTRAINT PK_LOC PRIMARY KEY (LOC);

ALTER TABLE ITEM_LOC_SOH ADD CONSTRAINT PK_ITEM_LOC_SOH PRIMARY KEY (ITEM, LOC);

CREATE INDEX ITEM_LOC_SOH_I1 ON ITEM_LOC_SOH(DEPT);